apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hans
  name: hans
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hans
  template:
    metadata:
      labels:
        app: hans
    spec:
      containers:
      - image: httpd:alpine3.19
        name: httpd
        command: ["/bin/bash", "-c"]
        args: ["sleep 5; exit 1"]
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1