version: ‘3.8’
services:
    db:
        container_name: wordpress-db
        image: mysql:5.7
        # Do not simply upgrade or downgrade, as the database will not load anymore.
        restart: always
        volumes:
            - /volume3/docker/wordpress_db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: password

    wordpress:
        container_name: wordpress
        depends_on:
            - db
        image: wordpress:latest
        ports:
            - 8020:80
        restart: always
        volumes:
            - /volume3/docker/wordpress_data:/var/www/html
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: VxixUhodRYrka6YbXGkV